name: deploy to sagemaker

on:
  repository_dispatch:
    types: [ mlflow_prod_trigger ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODEL_NAME: HRModel
      MODEL_URI: ${{ github.event.client_payload.model_uri }}
      ROLE_ARN: arn:aws:iam::236013686531:role/service-role/SageMaker-mlops-demo
      ENDPOINT_CONFIG_NAME: HRModel-endpoint-config
      ENDPOINT_NAME: HRModel-endpoint
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install requirements
      run: pip install --no-cache-dir -r requirements.txt
      
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        
    - name: Amazon ECR "Login" Action for GitHub Actions
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2.0.1

    - name: Create ECR Repository if not exists
      run: |
        aws ecr create-repository --repository-name mlflow --region ap-southeast-2 || true

    - name: Create S3 Bucket if not exists
      run: |
        aws s3 mb s3://package-model-for-sagemaker-deploy || true

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: mlflow
        IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
      run: |
        docker buildx build --platform linux/amd64 --provenance=false \
            --output "type=image, oci-mediatypes=false, push=true, name=$REGISTRY/$REPOSITORY:$IMAGE_TAG" .
        echo "image_uri=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Delete Existing SageMaker Model
      run: |
        aws sagemaker delete-model --model-name ${{ env.MODEL_NAME }} --region ap-southeast-2 || true

    - name: Create Sagemaker Model
      run: mlflow sagemaker push-model --model-name ${{ env.MODEL_NAME }} --model-uri ${{ env.MODEL_URI }} --execution-role-arn ${{ env.ROLE_ARN }} --image-url ${{ env.image_uri }} --region-name ap-southeast-2
    
    - name: Delete Existing Endpoint Configuration
      run: |
        aws sagemaker delete-endpoint-config --endpoint-config-name ${{ env.ENDPOINT_CONFIG_NAME }} --region ap-southeast-2 || true

    - name: Create Sagemaker Endpoint Configuration
      run: |
        aws sagemaker create-endpoint-config \
          --endpoint-config-name ${{ env.ENDPOINT_CONFIG_NAME }} \
          --production-variants '[{"VariantName":"AllTraffic","ModelName":"${{ env.MODEL_NAME }}","InstanceType":"ml.t2.medium","InitialInstanceCount":1}]' \
          --region ap-southeast-2

    - name: Delete Existing SageMaker Endpoint
      run: |
        aws sagemaker delete-endpoint --endpoint-name ${{ env.ENDPOINT_NAME }} --region ap-southeast-2 || true
        aws sagemaker wait endpoint-deleted --endpoint-name ${{ env.ENDPOINT_NAME }} --region ap-southeast-2 || true
        
    - name: Deploy Sagemaker Endpoint
      run: |
        aws sagemaker create-endpoint \
          --endpoint-name ${{ env.ENDPOINT_NAME }} \
          --endpoint-config-name ${{ env.ENDPOINT_CONFIG_NAME }} \
          --region ap-southeast-2

    - name: Wait for Endpoint
      run: |
        aws sagemaker wait endpoint-in-service --endpoint-name ${{ env.ENDPOINT_NAME }} --region ap-southeast-2